version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/theme"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(prod-deps): "
      prefix-development: "chore(dev-deps): "
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
    groups:
      all:

  - package-ecosystem: "maven"
    directory: "/extension"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(prod-deps): "
      prefix-development: "chore(dev-deps): "
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
