name: Pull Request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-commits:
    name: Check Commitizen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pyhon
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Commitizen
        run: ./.internal/ci/install-cz.sh

      - name: Check Commits
        run: ./.internal/ci/version-check.sh

  build-theme:
    name: Build Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build Theme
        run: ./.internal/ci/build-theme.sh

      - name: Rename Jar
        run: |
          mv ./theme/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar ./keycloak-app-passwords-theme.jar

      - name: Upload Jar
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: theme
          path: ./keycloak-app-passwords-theme.jar

  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest
    outputs:
      extension-artifact-name: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test Extension
        run: ./.internal/ci/build-extension.sh

      - name: Rename Jar
        run: |
          mv ./extension/target/keycloak-app-passwords-DEV.jar ./keycloak-app-passwords-extension.jar

      - name: Upload Jar
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ./keycloak-app-passwords-extension.jar

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    needs: [build-theme, build-extension]
    env:
      THEME_PATH: ./keycloak-app-passwords-theme.jar
      EXTENSION_PATH: ./keycloak-app-passwords-extension.jar
      CONFIG_PATH: ./keycloak-app-passwords.config.json
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Download Theme Jar
        uses: actions/download-artifact@v4
        with:
          name: theme
          path: ./extension

      - name: Download Extension Jar
        uses: actions/download-artifact@v4
        with:
          name: extension
          path: ./extension

      - name: Setup OpenLDAP
        run: ./.internal/ci/init-openldap.sh

      - name: Import Data
        run: ./.internal/ci/import-data.sh

      - name: Run Extension
        run: ./.internal/ci/run.sh

      - name: Install E2E
        run: ./.internal/ci/e2e-install.sh

      - name: Wait for Keycloak
        run: ./.internal/ci/e2e-wait-for-keycloak.sh

      - name: Reset Keycloak
        run: ./.internal/ci/keycloak-reset.sh

      - name: Test E2E
        run: ./.internal/ci/e2e.sh
